"""
BERT prediction and evaluation script for ontological security narrative classification.

This script loads fine-tuned BERT model directories generated by bert_train.py,
predicts labels for a fixed test set, and reports per-run and mean ± std
evaluation metrics.

Expected input columns:
- Text
- Label
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Iterable, List, Tuple

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    cohen_kappa_score,
    confusion_matrix,
    precision_recall_fscore_support,
)
from torch.utils.data import DataLoader, Dataset
from transformers import BertForSequenceClassification, BertTokenizer


DEFAULT_TEXT_COL = "Text"
DEFAULT_LABEL_COL = "Label"
DEFAULT_BATCH_SIZE = 8
DEFAULT_MAX_LEN = 128


class TextDataset(Dataset):
    """Dataset for BERT prediction."""

    def __init__(self, texts: List[str], tokenizer: BertTokenizer, max_len: int):
        self.texts = texts
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self) -> int:
        return len(self.texts)

    def __getitem__(self, idx: int) -> dict[str, torch.Tensor]:
        encoded = self.tokenizer(
            self.texts[idx],
            max_length=self.max_len,
            truncation=True,
            padding="max_length",
            return_tensors="pt",
        )

        return {
            "input_ids": encoded["input_ids"].squeeze(0),
            "attention_mask": encoded["attention_mask"].squeeze(0),
        }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate fine-tuned BERT runs on a fixed test set."
    )
    parser.add_argument(
        "--test-path",
        required=True,
        help="Path to the test Excel file.",
    )
    parser.add_argument(
        "--model-dir",
        default="models/bert",
        help="Directory containing run_XX model folders.",
    )
    parser.add_argument(
        "--output-dir",
        default="outputs/bert",
        help="Directory for prediction and evaluation outputs.",
    )
    parser.add_argument(
        "--run-dirs",
        default=None,
        help=(
            "Optional comma-separated run directories to evaluate, e.g., "
            "run_01,run_02. If omitted, all run_XX folders are used."
        ),
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help="Prediction batch size.",
    )
    parser.add_argument(
        "--max-len",
        type=int,
        default=DEFAULT_MAX_LEN,
        help="Maximum token length.",
    )
    parser.add_argument(
        "--text-col",
        default=DEFAULT_TEXT_COL,
        help="Name of the text column.",
    )
    parser.add_argument(
        "--label-col",
        default=DEFAULT_LABEL_COL,
        help="Name of the label column.",
    )
    return parser.parse_args()


def load_test_data(path: str | os.PathLike, text_col: str, label_col: str) -> pd.DataFrame:
    df = pd.read_excel(path)
    required_cols = {text_col, label_col}
    missing = required_cols.difference(df.columns)
    if missing:
        raise ValueError(
            f"Missing required column(s): {sorted(missing)}. "
            f"Available columns: {list(df.columns)}"
        )
    return df.dropna(subset=[text_col, label_col]).copy()


def load_label_info(model_path: Path, model_root: Path) -> tuple[List[str], dict[int, str]]:
    candidate_paths = [
        model_path / "label_map.json",
        model_root / "label_map.json",
    ]

    for path in candidate_paths:
        if path.exists():
            with path.open("r", encoding="utf-8") as f:
                info = json.load(f)

            labels = info["labels"]
            id2label = {int(k): v for k, v in info["id2label"].items()}
            return labels, id2label

    raise FileNotFoundError(
        "label_map.json was not found. Please run bert_train.py first."
    )


def find_model_paths(model_root: Path, run_dirs: str | None) -> List[Path]:
    if run_dirs:
        paths = [model_root / item.strip() for item in run_dirs.split(",") if item.strip()]
    else:
        paths = [
            model_root / name
            for name in sorted(os.listdir(model_root))
            if name.startswith("run_") and (model_root / name).is_dir()
        ]

    if not paths:
        raise FileNotFoundError(
            f"No run_XX model directories found under {model_root}. "
            "Please run bert_train.py first."
        )

    missing = [str(path) for path in paths if not path.exists()]
    if missing:
        raise FileNotFoundError(f"Missing model directories: {missing}")

    return paths


def format_confusion_matrix(cm: np.ndarray, labels: Iterable[str]) -> str:
    labels = list(labels)
    col_width = max(10, max(len(str(label)) for label in labels) + 2)
    header = " " * col_width + "".join(f"{label:>{col_width}}" for label in labels)
    rows = [header]

    for label, row in zip(labels, cm):
        rows.append(f"{label:<{col_width}}" + "".join(f"{int(v):>{col_width}}" for v in row))

    return "\n".join(rows)


def mean_std(values: Iterable[float]) -> Tuple[float, float]:
    values = np.array(list(values), dtype=float)
    if len(values) <= 1:
        return float(np.mean(values)), 0.0
    return float(np.mean(values)), float(np.std(values, ddof=1))


def predict_single_run(
    model_path: Path,
    texts: List[str],
    batch_size: int,
    max_len: int,
    device: torch.device,
) -> tuple[List[int], List[str], dict[int, str]]:
    labels, id2label = load_label_info(model_path, model_path.parent)

    tokenizer = BertTokenizer.from_pretrained(model_path)
    model = BertForSequenceClassification.from_pretrained(model_path).to(device)
    model.eval()

    dataset = TextDataset(texts, tokenizer, max_len)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    pred_ids = []

    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            logits = model(input_ids=input_ids, attention_mask=attention_mask).logits
            pred_ids.extend(torch.argmax(logits, dim=1).cpu().numpy().tolist())

    y_pred_labels = [id2label[int(i)] for i in pred_ids]
    return pred_ids, y_pred_labels, id2label


def main() -> None:
    args = parse_args()

    if args.batch_size < 1:
        raise ValueError("--batch-size must be at least 1.")
    if args.max_len < 1:
        raise ValueError("--max-len must be at least 1.")

    model_root = Path(args.model_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    test_df = load_test_data(args.test_path, args.text_col, args.label_col)
    texts = test_df[args.text_col].astype(str).tolist()
    y_true_labels = test_df[args.label_col].astype(str).str.strip().tolist()

    print(f"Test size: {len(test_df)}")
    print(f"Test distribution: {dict(pd.Series(y_true_labels).value_counts())}")

    model_paths = find_model_paths(model_root, args.run_dirs)
    print("Model runs found:", [path.name for path in model_paths])

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    metrics_rows = []
    all_text_blocks = []

    for model_path in model_paths:
        run_name = model_path.name
        print(f"\n===== Predicting {run_name} =====")

        labels, id2label = load_label_info(model_path, model_root)

        unknown_test_labels = sorted(set(y_true_labels).difference(labels))
        if unknown_test_labels:
            raise ValueError(
                f"The test set contains labels not included in the training label map: "
                f"{unknown_test_labels}"
            )

        _, y_pred_labels, _ = predict_single_run(
            model_path=model_path,
            texts=texts,
            batch_size=args.batch_size,
            max_len=args.max_len,
            device=device,
        )

        cm = confusion_matrix(y_true_labels, y_pred_labels, labels=labels)
        kappa = cohen_kappa_score(y_true_labels, y_pred_labels, labels=labels)
        accuracy = accuracy_score(y_true_labels, y_pred_labels)
        precision, recall, macro_f1, _ = precision_recall_fscore_support(
            y_true_labels,
            y_pred_labels,
            labels=labels,
            average="macro",
            zero_division=0,
        )

        report = classification_report(
            y_true_labels,
            y_pred_labels,
            labels=labels,
            digits=4,
            zero_division=0,
        )

        metrics_rows.append(
            {
                "run": run_name,
                "accuracy": accuracy,
                "macro_precision": precision,
                "macro_recall": recall,
                "macro_f1": macro_f1,
                "kappa": kappa,
            }
        )

        print(
            f"{run_name} | "
            f"Accuracy={accuracy:.4f}, "
            f"Macro-F1={macro_f1:.4f}, "
            f"Kappa={kappa:.4f}"
        )

        pred_df = test_df.copy()
        pred_df["Run"] = run_name
        pred_df["Pred_Label"] = y_pred_labels
        pred_df["Correct"] = (
            pred_df[args.label_col].astype(str).str.strip()
            == pred_df["Pred_Label"].astype(str).str.strip()
        ).astype(int)
        pred_df["Error_Type"] = np.where(
            pred_df["Correct"] == 1,
            "",
            pred_df[args.label_col].astype(str).str.strip()
            + " -> "
            + pred_df["Pred_Label"].astype(str).str.strip(),
        )

        pred_path = output_dir / f"bert_{run_name}_test_predictions_{timestamp}.xlsx"
        pred_df.to_excel(pred_path, index=False)

        block = []
        block.append(f"[{run_name}] Confusion Matrix")
        block.append("-" * 60)
        block.append("Rows = Ground Truth, Columns = Prediction")
        block.append("Labels: " + ", ".join(labels))
        block.append("")
        block.append(format_confusion_matrix(cm, labels))
        block.append("")
        block.append(f"Cohen's Kappa: {kappa:.6f}")
        block.append(f"Accuracy: {accuracy:.6f}")
        block.append(f"Macro Precision: {precision:.6f}")
        block.append(f"Macro Recall: {recall:.6f}")
        block.append(f"Macro F1: {macro_f1:.6f}")
        block.append("")
        block.append("Classification Report:")
        block.append("")
        block.append(report)
        block.append(f"Prediction Excel: {pred_path}")
        block.append("\n")
        all_text_blocks.append("\n".join(block))

    metrics_df = pd.DataFrame(metrics_rows)

    summary_rows = []
    for metric in ["accuracy", "macro_precision", "macro_recall", "macro_f1", "kappa"]:
        mean, std = mean_std(metrics_df[metric])
        summary_rows.append({"metric": metric, "mean": mean, "std": std})
    summary_df = pd.DataFrame(summary_rows)

    metrics_path = output_dir / f"bert_train_test_metrics_{timestamp}.xlsx"
    with pd.ExcelWriter(metrics_path, engine="openpyxl") as writer:
        metrics_df.to_excel(writer, sheet_name="per_run_metrics", index=False)
        summary_df.to_excel(writer, sheet_name="summary_mean_std", index=False)

    summary_text_lines = []
    summary_text_lines.append("BERT Train-Test Evaluation")
    summary_text_lines.append("=" * 60)
    summary_text_lines.append(f"Test path: {args.test_path}")
    summary_text_lines.append(f"Model dir: {args.model_dir}")
    summary_text_lines.append(f"Number of runs: {len(metrics_df)}")
    summary_text_lines.append("")
    summary_text_lines.append("[Summary: Mean ± Std]")
    summary_text_lines.append("-" * 60)

    for _, row in summary_df.iterrows():
        summary_text_lines.append(
            f"{row['metric']}: {row['mean']:.6f} ± {row['std']:.6f}"
        )

    summary_text_lines.append("\n")
    summary_text_lines.extend(all_text_blocks)

    txt_path = output_dir / f"bert_train_test_results_{timestamp}.txt"
    with txt_path.open("w", encoding="utf-8") as f:
        f.write("\n".join(summary_text_lines))

    print(f"\n[OK] Text report saved to: {txt_path}")
    print(f"[OK] Metrics Excel saved to: {metrics_path}")
    print("BERT prediction finished.")


if __name__ == "__main__":
    main()
